-- Cofradero · seed desactivado
--
-- Ya no insertamos datos de demo aquí.
-- Los foros, temas y respuestas se gestionan desde la app / Junta
-- y viven en Supabase.
--
-- Este archivo NO se ejecuta al reiniciar Flutter.
-- No lo lances en el SQL Editor salvo que sepas lo que haces.
--
-- Si necesitas recrear un entorno vacío desde cero:
-- 1) schema + migraciones SQL del repo
-- 2) crear foros / temas desde la Junta o la app
